<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Hr___Payroll</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Business - HR\Business - HR.csproj" />
    <ProjectReference Include="..\Business Payroll\Business Payroll.csproj" />
  </ItemGroup>

</Project>
